export { default as IcmsIpiEntrada } from './IcmsIpiEntrada.vue'
export { default as IcmsIpiSaida } from './IcmsIpiSaida.vue'
export { default as PisCofinsEntrada } from './PisCofinsEntrada.vue'
export { default as PisCofinsSaida } from './PisCofinsSaida.vue'
export { default as Home } from './Home.vue'
export { default as BankStatement } from './BankStatement.vue'
